server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_oven?useSSL=false&characterEncoding=utf8
    username: root
    password: xxc6711758
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

file:
  picture:
    path: /Users/liufeng/Pictures/

oven:
  maxNum: 20

jiguang:
  master_secret: *****
  app_key: *****
